//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum BodyID {
  CHASSIS_BODY = -99990,
  SPROCKET_BODY = -99991,
  IDLER_BODY = -99992,
  WHEEL_BODY = -99993,
  ROLER_BODY = -99994,
  SHOE_BODY = -99995
}
