//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ChLinkLinActuator : ChLinkLockLock {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal ChLinkLinActuator(global::System.IntPtr cPtr, bool cMemoryOwn) : base(corePINVOKE.ChLinkLinActuator_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ChLinkLinActuator obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          corePINVOKE.delete_ChLinkLinActuator(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public ChLinkLinActuator() : this(corePINVOKE.new_ChLinkLinActuator__SWIG_0(), true) {
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public ChLinkLinActuator(ChLinkLinActuator other) : this(corePINVOKE.new_ChLinkLinActuator__SWIG_1(ChLinkLinActuator.getCPtr(other)), true) {
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public override void UpdateTime(double mytime) {
    corePINVOKE.ChLinkLinActuator_UpdateTime(swigCPtr, mytime);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public ChFunction Get_dist_funct() {
    global::System.IntPtr cPtr = corePINVOKE.ChLinkLinActuator_Get_dist_funct(swigCPtr);
    ChFunction ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChFunction(cPtr, true);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ChFunction Get_motrot_funct() {
    global::System.IntPtr cPtr = corePINVOKE.ChLinkLinActuator_Get_motrot_funct(swigCPtr);
    ChFunction ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChFunction(cPtr, true);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ChFunction Get_mottorque_funct() {
    global::System.IntPtr cPtr = corePINVOKE.ChLinkLinActuator_Get_mottorque_funct(swigCPtr);
    ChFunction ret = (cPtr == global::System.IntPtr.Zero) ? null : new ChFunction(cPtr, true);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Set_dist_funct(ChFunction mf) {
    corePINVOKE.ChLinkLinActuator_Set_dist_funct(swigCPtr, ChFunction.getCPtr(mf));
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Set_motrot_funct(ChFunction mf) {
    corePINVOKE.ChLinkLinActuator_Set_motrot_funct(swigCPtr, ChFunction.getCPtr(mf));
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Set_mottorque_funct(ChFunction mf) {
    corePINVOKE.ChLinkLinActuator_Set_mottorque_funct(swigCPtr, ChFunction.getCPtr(mf));
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Get_learn() {
    bool ret = corePINVOKE.ChLinkLinActuator_Get_learn(swigCPtr);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Set_learn(bool mset) {
    corePINVOKE.ChLinkLinActuator_Set_learn(swigCPtr, mset);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Get_learn_torque_rotaton() {
    bool ret = corePINVOKE.ChLinkLinActuator_Get_learn_torque_rotaton(swigCPtr);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Set_learn_torque_rotaton(bool mset) {
    corePINVOKE.ChLinkLinActuator_Set_learn_torque_rotaton(swigCPtr, mset);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public double Get_lin_offset() {
    double ret = corePINVOKE.ChLinkLinActuator_Get_lin_offset(swigCPtr);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Set_lin_offset(double mset) {
    corePINVOKE.ChLinkLinActuator_Set_lin_offset(swigCPtr, mset);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Set_mot_tau(double mtau) {
    corePINVOKE.ChLinkLinActuator_Set_mot_tau(swigCPtr, mtau);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public double Get_mot_tau() {
    double ret = corePINVOKE.ChLinkLinActuator_Get_mot_tau(swigCPtr);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Set_mot_eta(double meta) {
    corePINVOKE.ChLinkLinActuator_Set_mot_eta(swigCPtr, meta);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public double Get_mot_eta() {
    double ret = corePINVOKE.ChLinkLinActuator_Get_mot_eta(swigCPtr);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Set_mot_inertia(double min) {
    corePINVOKE.ChLinkLinActuator_Set_mot_inertia(swigCPtr, min);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public double Get_mot_inertia() {
    double ret = corePINVOKE.ChLinkLinActuator_Get_mot_inertia(swigCPtr);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double Get_mot_rerot() {
    double ret = corePINVOKE.ChLinkLinActuator_Get_mot_rerot(swigCPtr);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double Get_mot_rerot_dt() {
    double ret = corePINVOKE.ChLinkLinActuator_Get_mot_rerot_dt(swigCPtr);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double Get_mot_rerot_dtdt() {
    double ret = corePINVOKE.ChLinkLinActuator_Get_mot_rerot_dtdt(swigCPtr);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double Get_mot_retorque() {
    double ret = corePINVOKE.ChLinkLinActuator_Get_mot_retorque(swigCPtr);
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void ArchiveOUT(SWIGTYPE_p_ChArchiveOut marchive) {
    corePINVOKE.ChLinkLinActuator_ArchiveOUT(swigCPtr, SWIGTYPE_p_ChArchiveOut.getCPtr(marchive));
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

  public override void ArchiveIN(SWIGTYPE_p_chrono__ChArchiveIn marchive) {
    corePINVOKE.ChLinkLinActuator_ArchiveIN(swigCPtr, SWIGTYPE_p_chrono__ChArchiveIn.getCPtr(marchive));
    if (corePINVOKE.SWIGPendingException.Pending) throw corePINVOKE.SWIGPendingException.Retrieve();
  }

}
